version: "3.1"

services:
  baget:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 7777:8000
    volumes:
      - ./data/pacakges:/var/baget/packages
      - ./data/baget.db:/var/baget/baget.db