version: "3.1"

services:
  baget:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 7777:80
    volumes:
      - ./settings/appsettings.json:/app/appsettings.json
      - /app/baget.db
      - /app/packages

