version: "3.1"

services:
  baget:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      -  AllowPackageOverwrites=true
      -  ApiKeyHash=658489D79E218D2474D049E8729198D86DB0A4AF43981686A31C7DCB02DC0100
    ports:
      - 7777:8000
    volumes:
      - ./data/pacakges:/var/baget/packages
      - ./data/baget.db:/var/baget/baget.db